/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Pkp
 */
public class Page4ManualMathScienceFrame extends javax.swing.JFrame {

    /**
     * Creates new form page4_frame
     */
    public Page4ManualMathScienceFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        buttonGroup4 = new javax.swing.ButtonGroup();
        buttonGroup5 = new javax.swing.ButtonGroup();
        buttonGroup6 = new javax.swing.ButtonGroup();
        buttonGroup7 = new javax.swing.ButtonGroup();
        SCRkucha1kuchLine = new javax.swing.JButton();
        SCRkucha1kuchArc = new javax.swing.JButton();
        SCRkucha1kuchRegion = new javax.swing.JButton();
        SCRkucha1kuchdelete_page4 = new javax.swing.JButton();
        SCRkucha2kuchjScrollPane1 = new javax.swing.JScrollPane();
        jLabel1 = new javax.swing.JLabel();
        SCRkucha1kuchGo_back_page4 = new javax.swing.JButton();
        SCRkucha1kuchNext_page4 = new javax.swing.JButton();
        SCRkucha1kuchPath = new javax.swing.JButton();
        SCRkucha1kuchpolygon_start = new javax.swing.JRadioButton();
        SCRkucha1kuchpolygon_end = new javax.swing.JRadioButton();
        SCRkucha1kuchpreview_button = new javax.swing.JLabel();
        SCRkucha1kuchPolygon = new javax.swing.JButton();
        SCRkucha1kuchCircle = new javax.swing.JButton();
        SCRkucha1kuchzoom_slider = new javax.swing.JSlider();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        SCRkucha1kuchLine.setText("Line");
        SCRkucha1kuchLine.setToolTipText("Select two end points");

        SCRkucha1kuchArc.setText("Arc");
        SCRkucha1kuchArc.setToolTipText("Select three points of arc in order");
        SCRkucha1kuchArc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SCRkucha1kuchArcActionPerformed(evt);
            }
        });

        SCRkucha1kuchRegion.setText("Region");
        SCRkucha1kuchRegion.setToolTipText("Draw a arbit shape");

        SCRkucha1kuchdelete_page4.setText("Delete");
        SCRkucha1kuchdelete_page4.setToolTipText("Delete selected shapes");

        SCRkucha2kuchjScrollPane1.setViewportView(jLabel1);

        SCRkucha1kuchGo_back_page4.setText("Go Back");
        SCRkucha1kuchGo_back_page4.setToolTipText("Revert back to previous stage");
        SCRkucha1kuchGo_back_page4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SCRkucha1kuchGo_back_page4ActionPerformed(evt);
            }
        });

        SCRkucha1kuchNext_page4.setText("Next");
        SCRkucha1kuchNext_page4.setToolTipText("Go to next page if all shapes have been identified");

        SCRkucha1kuchPath.setText("Path");

        SCRkucha1kuchpolygon_start.setText("Start");

        SCRkucha1kuchpolygon_end.setText("End");
        SCRkucha1kuchpolygon_end.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SCRkucha1kuchpolygon_endActionPerformed(evt);
            }
        });

        SCRkucha1kuchpreview_button.setIcon(new javax.swing.ImageIcon("E:\\Acads\\CSD750\\BANA_28_05\\resources\\Images\\preview1_65x65.png")); // NOI18N

        SCRkucha1kuchPolygon.setText("Polygon");
        SCRkucha1kuchPolygon.setToolTipText("Select vertices of poygon in an order");
        SCRkucha1kuchPolygon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SCRkucha1kuchPolygonActionPerformed(evt);
            }
        });

        SCRkucha1kuchCircle.setText("Circle");
        SCRkucha1kuchCircle.setToolTipText("Select any three point of circle");

        SCRkucha1kuchzoom_slider.setMajorTickSpacing(5);
        SCRkucha1kuchzoom_slider.setMaximum(36);
        SCRkucha1kuchzoom_slider.setMinimum(1);
        SCRkucha1kuchzoom_slider.setMinorTickSpacing(1);
        SCRkucha1kuchzoom_slider.setOrientation(javax.swing.JSlider.VERTICAL);
        SCRkucha1kuchzoom_slider.setPaintLabels(true);
        SCRkucha1kuchzoom_slider.setPaintTicks(true);
        SCRkucha1kuchzoom_slider.setValue(16);

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(SCRkucha1kuchGo_back_page4, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SCRkucha1kuchLine, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SCRkucha1kuchCircle, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SCRkucha1kuchPolygon, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SCRkucha1kuchArc, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SCRkucha1kuchpolygon_start, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SCRkucha1kuchpolygon_end, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SCRkucha1kuchPath, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SCRkucha1kuchRegion, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SCRkucha1kuchdelete_page4, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19)
                .addComponent(SCRkucha2kuchjScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(SCRkucha1kuchpreview_button, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(SCRkucha1kuchzoom_slider, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap())
                    .addComponent(SCRkucha1kuchNext_page4, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(SCRkucha2kuchjScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(SCRkucha1kuchGo_back_page4)
                .addGap(16, 16, 16)
                .addComponent(SCRkucha1kuchLine)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(SCRkucha1kuchCircle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(SCRkucha1kuchArc)
                .addGap(18, 18, 18)
                .addComponent(SCRkucha1kuchPolygon)
                .addGap(18, 18, 18)
                .addComponent(SCRkucha1kuchpolygon_start)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(SCRkucha1kuchpolygon_end)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(SCRkucha1kuchPath)
                .addGap(18, 18, 18)
                .addComponent(SCRkucha1kuchRegion)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(SCRkucha1kuchdelete_page4)
                .addGap(23, 23, 23))
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(SCRkucha1kuchNext_page4)
                .addGap(63, 63, 63)
                .addComponent(SCRkucha1kuchpreview_button)
                .addGap(61, 61, 61)
                .addComponent(SCRkucha1kuchzoom_slider, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SCRkucha1kuchGo_back_page4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SCRkucha1kuchGo_back_page4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SCRkucha1kuchGo_back_page4ActionPerformed

    private void SCRkucha1kuchpolygon_endActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SCRkucha1kuchpolygon_endActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SCRkucha1kuchpolygon_endActionPerformed

    private void SCRkucha1kuchArcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SCRkucha1kuchArcActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SCRkucha1kuchArcActionPerformed

    private void SCRkucha1kuchPolygonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SCRkucha1kuchPolygonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SCRkucha1kuchPolygonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Page4ManualMathScienceFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Page4ManualMathScienceFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Page4ManualMathScienceFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Page4ManualMathScienceFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Page4ManualMathScienceFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton SCRkucha1kuchArc;
    private javax.swing.JButton SCRkucha1kuchCircle;
    private javax.swing.JButton SCRkucha1kuchGo_back_page4;
    private javax.swing.JButton SCRkucha1kuchLine;
    private javax.swing.JButton SCRkucha1kuchNext_page4;
    private javax.swing.JButton SCRkucha1kuchPath;
    private javax.swing.JButton SCRkucha1kuchPolygon;
    private javax.swing.JButton SCRkucha1kuchRegion;
    private javax.swing.JButton SCRkucha1kuchdelete_page4;
    private javax.swing.JRadioButton SCRkucha1kuchpolygon_end;
    private javax.swing.JRadioButton SCRkucha1kuchpolygon_start;
    private javax.swing.JLabel SCRkucha1kuchpreview_button;
    private javax.swing.JSlider SCRkucha1kuchzoom_slider;
    private javax.swing.JScrollPane SCRkucha2kuchjScrollPane1;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.ButtonGroup buttonGroup4;
    private javax.swing.ButtonGroup buttonGroup5;
    private javax.swing.ButtonGroup buttonGroup6;
    private javax.swing.ButtonGroup buttonGroup7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    // End of variables declaration//GEN-END:variables
}
